<?xml version="1.0" encoding="utf-8"?>
<!-- Generated by Random3Dcity (http://github.com/tudelft3d/Random3Dcity), a tool developed by Filip Biljecki at TU Delft. Version: 2015-03-11. -->
<CityModel xmlns:veg="http://www.opengis.net/citygml/vegetation/2.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xAL="urn:oasis:names:tc:ciq:xsdschema:xAL:2.0" xmlns:dem="http://www.opengis.net/citygml/relief/2.0" xmlns:gml="http://www.opengis.net/gml" xmlns:fme="http://www.safe.com/xml/xmltables" xmlns:tran="http://www.opengis.net/citygml/transportation/2.0" xmlns:bldg="http://www.opengis.net/citygml/building/2.0" xmlns:xlink="http://www.w3.org/1999/xlink" xmlns="http://www.opengis.net/citygml/2.0">
  <gml:name>LOD1_0_HMin</gml:name>
  <gml:boundedBy>
    <gml:Envelope srsDimension="3" srsName="EPSG:28992">
      <gml:lowerCorner>0 0 0</gml:lowerCorner>
      <gml:upperCorner>4000 4000 25</gml:upperCorner>
    </gml:Envelope>
  </gml:boundedBy>
  <cityObjectMember>
    <bldg:Building gml:id="d7c0e63f-6ec7-4ae9-926b-462f476c8c3a">
      <bldg:roofType>Flat</bldg:roofType>
      <bldg:yearOfConstruction>1963</bldg:yearOfConstruction>
      <bldg:function>Residential</bldg:function>
      <bldg:storeysAboveGround>2</bldg:storeysAboveGround>
      <bldg:lod1MultiSurface>
        <gml:MultiSurface>
          <gml:surfaceMember>
            <gml:Polygon gml:id="ecf361c0-4ac0-4b37-9304-bae740a9cb09">
              <gml:exterior>
                <gml:LinearRing>
                  <gml:posList>0.0 0.0 0.0 54.0 0.0 0.0 54.0 0.0 6.37974842767 0.0 0.0 6.37974842767 0.0 0.0 0.0</gml:posList>
                </gml:LinearRing>
              </gml:exterior>
            </gml:Polygon>
            <gml:Polygon gml:id="024d2e2b-549c-4c66-9a4e-66d80843f829">
              <gml:exterior>
                <gml:LinearRing>
                  <gml:posList>54.0 54.0 0.0 0.0 54.0 0.0 0.0 54.0 6.37974842767 54.0 54.0 6.37974842767 54.0 54.0 0.0</gml:posList>
                </gml:LinearRing>
              </gml:exterior>
            </gml:Polygon>
            <gml:Polygon gml:id="cb78bdc4-ce23-4ae9-bdfd-f0c1deb268db">
              <gml:exterior>
                <gml:LinearRing>
                  <gml:posList>0.0 54.0 0.0 0.0 0.0 0.0 0.0 0.0 6.37974842767 0.0 54.0 6.37974842767 0.0 54.0 0.0</gml:posList>
                </gml:LinearRing>
              </gml:exterior>
            </gml:Polygon>
            <gml:Polygon gml:id="68144e13-8b31-4bf9-9871-7618f8941a95">
              <gml:exterior>
                <gml:LinearRing>
                  <gml:posList>54.0 0.0 0.0 54.0 54.0 0.0 54.0 54.0 6.37974842767 54.0 0.0 6.37974842767 54.0 0.0 0.0</gml:posList>
                </gml:LinearRing>
              </gml:exterior>
            </gml:Polygon>
            <gml:Polygon gml:id="aa258e01-5c24-46e6-a7d6-19090801a3ff">
              <gml:exterior>
                <gml:LinearRing>
                  <gml:posList>0.0 0.0 0.0 0.0 54.0 0.0 54.0 54.0 0.0 54.0 0.0 0.0 0.0 0.0 0.0</gml:posList>
                </gml:LinearRing>
              </gml:exterior>
            </gml:Polygon>
            <gml:Polygon gml:id="ead603ee-ec5f-4f8f-abef-fa9ed820d354">
              <gml:exterior>
                <gml:LinearRing>
                  <gml:posList>0.0 0.0 6.37974842767 54.0 0.0 6.37974842767 54.0 54.0 6.37974842767 0.0 54.0 6.37974842767 0.0 0.0 6.37974842767</gml:posList>
                </gml:LinearRing>
              </gml:exterior>
            </gml:Polygon>
          </gml:surfaceMember>
        </gml:MultiSurface>
      </bldg:lod1MultiSurface>
    </bldg:Building>
  </cityObjectMember>
  <cityObjectMember>
    <bldg:Building gml:id="57a35cd2-2307-4dc8-9081-d3bb5ae7f6e2">
      <bldg:roofType>Flat</bldg:roofType>
      <bldg:yearOfConstruction>1996</bldg:yearOfConstruction>
      <bldg:function>Residential</bldg:function>
      <bldg:storeysAboveGround>5</bldg:storeysAboveGround>
      <bldg:lod1MultiSurface>
        <gml:MultiSurface>
          <gml:surfaceMember>
            <gml:Polygon gml:id="bc2143e9-e55d-4733-97f0-82de13878829">
              <gml:exterior>
                <gml:LinearRing>
                  <gml:posList>60.0 0.0 0.0 114.0 0.0 0.0 114.0 0.0 17.05 60.0 0.0 17.05 60.0 0.0 0.0</gml:posList>
                </gml:LinearRing>
              </gml:exterior>
            </gml:Polygon>
            <gml:Polygon gml:id="8e8cbbd7-a7c3-47de-9a93-0c901da09ebc">
              <gml:exterior>
                <gml:LinearRing>
                  <gml:posList>114.0 54.0 0.0 60.0 54.0 0.0 60.0 54.0 17.05 114.0 54.0 17.05 114.0 54.0 0.0</gml:posList>
                </gml:LinearRing>
              </gml:exterior>
            </gml:Polygon>
            <gml:Polygon gml:id="a5ba9d92-8211-49af-9fe6-d2a0c6b95fd6">
              <gml:exterior>
                <gml:LinearRing>
                  <gml:posList>60.0 54.0 0.0 60.0 0.0 0.0 60.0 0.0 17.05 60.0 54.0 17.05 60.0 54.0 0.0</gml:posList>
                </gml:LinearRing>
              </gml:exterior>
            </gml:Polygon>
            <gml:Polygon gml:id="5a2421e5-21b0-4d93-b01f-cc9bc5ae295d">
              <gml:exterior>
                <gml:LinearRing>
                  <gml:posList>114.0 0.0 0.0 114.0 54.0 0.0 114.0 54.0 17.05 114.0 0.0 17.05 114.0 0.0 0.0</gml:posList>
                </gml:LinearRing>
              </gml:exterior>
            </gml:Polygon>
            <gml:Polygon gml:id="cc6f5035-69b6-49d9-b073-bbdb2ef9a74c">
              <gml:exterior>
                <gml:LinearRing>
                  <gml:posList>60.0 0.0 0.0 60.0 54.0 0.0 114.0 54.0 0.0 114.0 0.0 0.0 60.0 0.0 0.0</gml:posList>
                </gml:LinearRing>
              </gml:exterior>
            </gml:Polygon>
            <gml:Polygon gml:id="c86978e4-c4b5-4ca3-aaaa-47078e22b6d2">
              <gml:exterior>
                <gml:LinearRing>
                  <gml:posList>60.0 0.0 17.05 114.0 0.0 17.05 114.0 54.0 17.05 60.0 54.0 17.05 60.0 0.0 17.05</gml:posList>
                </gml:LinearRing>
              </gml:exterior>
            </gml:Polygon>
          </gml:surfaceMember>
        </gml:MultiSurface>
      </bldg:lod1MultiSurface>
    </bldg:Building>
  </cityObjectMember>
</CityModel>
