<?xml version="1.0" encoding="utf-8"?>
<!-- Generated by Random3Dcity (http://github.com/tudelft3d/Random3Dcity), a tool developed by Filip Biljecki at TU Delft. Version: 2015-03-11. -->
<CityModel xmlns:veg="http://www.opengis.net/citygml/vegetation/2.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xAL="urn:oasis:names:tc:ciq:xsdschema:xAL:2.0" xmlns:dem="http://www.opengis.net/citygml/relief/2.0" xmlns:gml="http://www.opengis.net/gml" xmlns:fme="http://www.safe.com/xml/xmltables" xmlns:tran="http://www.opengis.net/citygml/transportation/2.0" xmlns:bldg="http://www.opengis.net/citygml/building/2.0" xmlns:xlink="http://www.w3.org/1999/xlink" xmlns="http://www.opengis.net/citygml/2.0">
  <gml:name>LOD0_2_F0_H3</gml:name>
  <gml:boundedBy>
    <gml:Envelope srsDimension="3" srsName="EPSG:28992">
      <gml:lowerCorner>0 0 0</gml:lowerCorner>
      <gml:upperCorner>4000 4000 25</gml:upperCorner>
    </gml:Envelope>
  </gml:boundedBy>
  <cityObjectMember>
    <bldg:Building gml:id="d7c0e63f-6ec7-4ae9-926b-462f476c8c3a">
      <bldg:roofType>Hipped</bldg:roofType>
      <bldg:yearOfConstruction>1963</bldg:yearOfConstruction>
      <bldg:function>Residential</bldg:function>
      <bldg:storeysAboveGround>2</bldg:storeysAboveGround>
      <bldg:storeysAboveGround>2</bldg:storeysAboveGround>
      <bldg:lod0FootPrint>
        <gml:MultiSurface>
          <gml:surfaceMember>
            <gml:Polygon gml:id="c4c47916-55a0-4292-9583-e401173879c4">
              <gml:exterior>
                <gml:LinearRing>
                  <gml:posList>0.0 0.0 0.0 7.95 0.0 0.0 7.95 6.11 0.0 0.0 6.11 0.0 0.0 0.0 0.0</gml:posList>
                </gml:LinearRing>
              </gml:exterior>
            </gml:Polygon>
          </gml:surfaceMember>
        </gml:MultiSurface>
      </bldg:lod0FootPrint>
      <bldg:lod0RoofEdge>
        <gml:MultiSurface>
          <gml:surfaceMember>
            <gml:Polygon gml:id="784bdf80-4d44-493d-a3b3-3296563f5ad4">
              <gml:exterior>
                <gml:LinearRing>
                  <gml:posList>0.0 0.0 7.65487421384 7.95 0.0 7.65487421384 7.95 6.11 7.65487421384 0.0 6.11 7.65487421384 0.0 0.0 7.65487421384</gml:posList>
                </gml:LinearRing>
              </gml:exterior>
            </gml:Polygon>
          </gml:surfaceMember>
        </gml:MultiSurface>
      </bldg:lod0RoofEdge>
    </bldg:Building>
  </cityObjectMember>
  <cityObjectMember>
    <bldg:Building gml:id="693f46c0-a345-478a-93b0-ea01615fb40c">
      <bldg:roofType>Shed</bldg:roofType>
      <bldg:yearOfConstruction>2009</bldg:yearOfConstruction>
      <bldg:function>Residential</bldg:function>
      <bldg:storeysAboveGround>2</bldg:storeysAboveGround>
      <bldg:storeysAboveGround>2</bldg:storeysAboveGround>
      <bldg:lod0FootPrint>
        <gml:MultiSurface>
          <gml:surfaceMember>
            <gml:Polygon gml:id="d84f72e2-7dc8-4a3c-951c-f1bffc5a6f05">
              <gml:exterior>
                <gml:LinearRing>
                  <gml:posList>0.0 20.0 0.0 9.27 20.0 0.0 9.27 28.61 0.0 0.0 28.61 0.0 0.0 20.0 0.0</gml:posList>
                </gml:LinearRing>
              </gml:exterior>
            </gml:Polygon>
          </gml:surfaceMember>
        </gml:MultiSurface>
      </bldg:lod0FootPrint>
      <bldg:lod0RoofEdge>
        <gml:MultiSurface>
          <gml:surfaceMember>
            <gml:Polygon gml:id="257e8c60-c334-458d-95d0-74e718c6cafc">
              <gml:exterior>
                <gml:LinearRing>
                  <gml:posList>0.0 20.0 8.145 9.27 20.0 8.145 9.27 28.61 8.145 0.0 28.61 8.145 0.0 20.0 8.145</gml:posList>
                </gml:LinearRing>
              </gml:exterior>
            </gml:Polygon>
          </gml:surfaceMember>
        </gml:MultiSurface>
      </bldg:lod0RoofEdge>
    </bldg:Building>
  </cityObjectMember>
  <cityObjectMember>
    <bldg:Building gml:id="e5f72295-e816-4b06-a0d1-2453f5e453bb">
      <bldg:roofType>Gabled</bldg:roofType>
      <bldg:yearOfConstruction>2002</bldg:yearOfConstruction>
      <bldg:function>Residential</bldg:function>
      <bldg:storeysAboveGround>2</bldg:storeysAboveGround>
      <bldg:storeysAboveGround>2</bldg:storeysAboveGround>
      <bldg:lod0FootPrint>
        <gml:MultiSurface>
          <gml:surfaceMember>
            <gml:Polygon gml:id="c446f0f2-c97d-4bc9-9fc2-baf3972ab6a8">
              <gml:exterior>
                <gml:LinearRing>
                  <gml:posList>0.0 40.0 0.0 5.84 40.0 0.0 5.84 47.13 0.0 0.0 47.13 0.0 0.0 40.0 0.0</gml:posList>
                </gml:LinearRing>
              </gml:exterior>
            </gml:Polygon>
          </gml:surfaceMember>
        </gml:MultiSurface>
      </bldg:lod0FootPrint>
      <bldg:lod0RoofEdge>
        <gml:MultiSurface>
          <gml:surfaceMember>
            <gml:Polygon gml:id="436ae34f-7919-4c54-b8dd-8cfa1dc97923">
              <gml:exterior>
                <gml:LinearRing>
                  <gml:posList>0.0 40.0 7.5875 5.84 40.0 7.5875 5.84 47.13 7.5875 0.0 47.13 7.5875 0.0 40.0 7.5875</gml:posList>
                </gml:LinearRing>
              </gml:exterior>
            </gml:Polygon>
          </gml:surfaceMember>
        </gml:MultiSurface>
      </bldg:lod0RoofEdge>
    </bldg:Building>
  </cityObjectMember>
  <cityObjectMember>
    <bldg:Building gml:id="6ca837fc-523d-4217-b82d-4906fb0404fd">
      <bldg:roofType>Shed</bldg:roofType>
      <bldg:yearOfConstruction>1948</bldg:yearOfConstruction>
      <bldg:function>Residential</bldg:function>
      <bldg:storeysAboveGround>2</bldg:storeysAboveGround>
      <bldg:storeysAboveGround>2</bldg:storeysAboveGround>
      <bldg:lod0FootPrint>
        <gml:MultiSurface>
          <gml:surfaceMember>
            <gml:Polygon gml:id="084cd86e-5008-4de8-b1ee-95c9df7fe21e">
              <gml:exterior>
                <gml:LinearRing>
                  <gml:posList>20.0 0.0 0.0 23.72 0.0 0.0 23.72 9.83 0.0 20.0 9.83 0.0 20.0 0.0 0.0</gml:posList>
                </gml:LinearRing>
              </gml:exterior>
            </gml:Polygon>
          </gml:surfaceMember>
        </gml:MultiSurface>
      </bldg:lod0FootPrint>
      <bldg:lod0RoofEdge>
        <gml:MultiSurface>
          <gml:surfaceMember>
            <gml:Polygon gml:id="a68a7475-b260-46cb-84f6-e82f2aef5733">
              <gml:exterior>
                <gml:LinearRing>
                  <gml:posList>20.0 0.0 8.57 23.72 0.0 8.57 23.72 9.83 8.57 20.0 9.83 8.57 20.0 0.0 8.57</gml:posList>
                </gml:LinearRing>
              </gml:exterior>
            </gml:Polygon>
          </gml:surfaceMember>
        </gml:MultiSurface>
      </bldg:lod0RoofEdge>
    </bldg:Building>
  </cityObjectMember>
  <cityObjectMember>
    <bldg:Building gml:id="37b27226-1d6a-40ae-9a8e-df67172b9e76">
      <bldg:roofType>Flat</bldg:roofType>
      <bldg:yearOfConstruction>1955</bldg:yearOfConstruction>
      <bldg:function>Industrial</bldg:function>
      <bldg:storeysAboveGround>4</bldg:storeysAboveGround>
      <bldg:storeysAboveGround>4</bldg:storeysAboveGround>
      <bldg:lod0FootPrint>
        <gml:MultiSurface>
          <gml:surfaceMember>
            <gml:Polygon gml:id="af53c366-a141-4c0d-b929-148a7dddb67c">
              <gml:exterior>
                <gml:LinearRing>
                  <gml:posList>20.0 20.0 0.0 25.17 20.0 0.0 25.17 24.23 0.0 20.0 24.23 0.0 20.0 20.0 0.0</gml:posList>
                </gml:LinearRing>
              </gml:exterior>
            </gml:Polygon>
          </gml:surfaceMember>
        </gml:MultiSurface>
      </bldg:lod0FootPrint>
      <bldg:lod0RoofEdge>
        <gml:MultiSurface>
          <gml:surfaceMember>
            <gml:Polygon gml:id="f0c1c5c5-d7fe-47bd-acc1-6a52aeb991b4">
              <gml:exterior>
                <gml:LinearRing>
                  <gml:posList>20.0 20.0 13.2 25.17 20.0 13.2 25.17 24.23 13.2 20.0 24.23 13.2 20.0 20.0 13.2</gml:posList>
                </gml:LinearRing>
              </gml:exterior>
            </gml:Polygon>
          </gml:surfaceMember>
        </gml:MultiSurface>
      </bldg:lod0RoofEdge>
    </bldg:Building>
  </cityObjectMember>
  <cityObjectMember>
    <bldg:Building gml:id="353a591b-01e4-49a6-8fd3-360313f6ca7f">
      <bldg:roofType>Hipped</bldg:roofType>
      <bldg:yearOfConstruction>1988</bldg:yearOfConstruction>
      <bldg:function>Residential</bldg:function>
      <bldg:storeysAboveGround>2</bldg:storeysAboveGround>
      <bldg:storeysAboveGround>2</bldg:storeysAboveGround>
      <bldg:lod0FootPrint>
        <gml:MultiSurface>
          <gml:surfaceMember>
            <gml:Polygon gml:id="3d4cc9d3-4dab-4392-96d6-29ae22ce54ca">
              <gml:exterior>
                <gml:LinearRing>
                  <gml:posList>20.0 40.0 0.0 24.05 40.0 0.0 24.05 49.63 0.0 20.0 49.63 0.0 20.0 40.0 0.0</gml:posList>
                </gml:LinearRing>
              </gml:exterior>
            </gml:Polygon>
          </gml:surfaceMember>
        </gml:MultiSurface>
      </bldg:lod0FootPrint>
      <bldg:lod0RoofEdge>
        <gml:MultiSurface>
          <gml:surfaceMember>
            <gml:Polygon gml:id="d52e93fe-9e0b-4f60-9e16-15519291f22e">
              <gml:exterior>
                <gml:LinearRing>
                  <gml:posList>20.0 40.0 7.75197530864 24.05 40.0 7.75197530864 24.05 49.63 7.75197530864 20.0 49.63 7.75197530864 20.0 40.0 7.75197530864</gml:posList>
                </gml:LinearRing>
              </gml:exterior>
            </gml:Polygon>
          </gml:surfaceMember>
        </gml:MultiSurface>
      </bldg:lod0RoofEdge>
    </bldg:Building>
  </cityObjectMember>
  <cityObjectMember>
    <bldg:Building gml:id="249246ba-d9f5-48e8-8b69-1c0677375c5a">
      <bldg:roofType>Flat</bldg:roofType>
      <bldg:yearOfConstruction>2004</bldg:yearOfConstruction>
      <bldg:function>Industrial</bldg:function>
      <bldg:storeysAboveGround>5</bldg:storeysAboveGround>
      <bldg:storeysAboveGround>5</bldg:storeysAboveGround>
      <bldg:lod0FootPrint>
        <gml:MultiSurface>
          <gml:surfaceMember>
            <gml:Polygon gml:id="5489b124-d2a6-428c-95c0-542898c3b743">
              <gml:exterior>
                <gml:LinearRing>
                  <gml:posList>40.0 0.0 0.0 46.11 0.0 0.0 46.11 3.68 0.0 40.0 3.68 0.0 40.0 0.0 0.0</gml:posList>
                </gml:LinearRing>
              </gml:exterior>
            </gml:Polygon>
          </gml:surfaceMember>
        </gml:MultiSurface>
      </bldg:lod0FootPrint>
      <bldg:lod0RoofEdge>
        <gml:MultiSurface>
          <gml:surfaceMember>
            <gml:Polygon gml:id="7ca236e6-9d28-43b2-bcf7-d9260742001e">
              <gml:exterior>
                <gml:LinearRing>
                  <gml:posList>40.0 0.0 16.6 46.11 0.0 16.6 46.11 3.68 16.6 40.0 3.68 16.6 40.0 0.0 16.6</gml:posList>
                </gml:LinearRing>
              </gml:exterior>
            </gml:Polygon>
          </gml:surfaceMember>
        </gml:MultiSurface>
      </bldg:lod0RoofEdge>
    </bldg:Building>
  </cityObjectMember>
  <cityObjectMember>
    <bldg:Building gml:id="0d252789-4485-452f-85e1-52c5eb975b10">
      <bldg:roofType>Flat</bldg:roofType>
      <bldg:yearOfConstruction>1948</bldg:yearOfConstruction>
      <bldg:function>Residential</bldg:function>
      <bldg:storeysAboveGround>2</bldg:storeysAboveGround>
      <bldg:storeysAboveGround>2</bldg:storeysAboveGround>
      <bldg:lod0FootPrint>
        <gml:MultiSurface>
          <gml:surfaceMember>
            <gml:Polygon gml:id="3deac8eb-b740-49b2-a2a7-a221c9f6ddb7">
              <gml:exterior>
                <gml:LinearRing>
                  <gml:posList>40.0 20.0 0.0 48.21 20.0 0.0 48.21 29.57 0.0 40.0 29.57 0.0 40.0 20.0 0.0</gml:posList>
                </gml:LinearRing>
              </gml:exterior>
            </gml:Polygon>
          </gml:surfaceMember>
        </gml:MultiSurface>
      </bldg:lod0FootPrint>
      <bldg:lod0RoofEdge>
        <gml:MultiSurface>
          <gml:surfaceMember>
            <gml:Polygon gml:id="7ffeaedc-a9c9-4dd4-8ec5-565384941613">
              <gml:exterior>
                <gml:LinearRing>
                  <gml:posList>40.0 20.0 6.98 48.21 20.0 6.98 48.21 29.57 6.98 40.0 29.57 6.98 40.0 20.0 6.98</gml:posList>
                </gml:LinearRing>
              </gml:exterior>
            </gml:Polygon>
          </gml:surfaceMember>
        </gml:MultiSurface>
      </bldg:lod0RoofEdge>
    </bldg:Building>
  </cityObjectMember>
  <cityObjectMember>
    <bldg:Building gml:id="5644769e-43bd-4244-9984-56f1e99ab43e">
      <bldg:roofType>Flat</bldg:roofType>
      <bldg:yearOfConstruction>1962</bldg:yearOfConstruction>
      <bldg:function>Residential</bldg:function>
      <bldg:storeysAboveGround>5</bldg:storeysAboveGround>
      <bldg:storeysAboveGround>5</bldg:storeysAboveGround>
      <bldg:lod0FootPrint>
        <gml:MultiSurface>
          <gml:surfaceMember>
            <gml:Polygon gml:id="0a6f3c94-d895-41b4-8282-197eda2ae360">
              <gml:exterior>
                <gml:LinearRing>
                  <gml:posList>40.0 40.0 0.0 45.07 40.0 0.0 45.07 48.57 0.0 40.0 48.57 0.0 40.0 40.0 0.0</gml:posList>
                </gml:LinearRing>
              </gml:exterior>
            </gml:Polygon>
          </gml:surfaceMember>
        </gml:MultiSurface>
      </bldg:lod0FootPrint>
      <bldg:lod0RoofEdge>
        <gml:MultiSurface>
          <gml:surfaceMember>
            <gml:Polygon gml:id="74ab40cb-39f1-4184-82d9-6e67da946bea">
              <gml:exterior>
                <gml:LinearRing>
                  <gml:posList>40.0 40.0 16.1 45.07 40.0 16.1 45.07 48.57 16.1 40.0 48.57 16.1 40.0 40.0 16.1</gml:posList>
                </gml:LinearRing>
              </gml:exterior>
            </gml:Polygon>
          </gml:surfaceMember>
        </gml:MultiSurface>
      </bldg:lod0RoofEdge>
    </bldg:Building>
  </cityObjectMember>
  <cityObjectMember>
    <bldg:Building gml:id="57a35cd2-2307-4dc8-9081-d3bb5ae7f6e2">
      <bldg:roofType>Flat</bldg:roofType>
      <bldg:yearOfConstruction>1996</bldg:yearOfConstruction>
      <bldg:function>Residential</bldg:function>
      <bldg:storeysAboveGround>5</bldg:storeysAboveGround>
      <bldg:storeysAboveGround>5</bldg:storeysAboveGround>
      <bldg:lod0FootPrint>
        <gml:MultiSurface>
          <gml:surfaceMember>
            <gml:Polygon gml:id="e67b6601-ae50-494f-a4a5-cd9b01cfea45">
              <gml:exterior>
                <gml:LinearRing>
                  <gml:posList>60.0 0.0 0.0 68.67 0.0 0.0 68.67 7.37 0.0 60.0 7.37 0.0 60.0 0.0 0.0</gml:posList>
                </gml:LinearRing>
              </gml:exterior>
            </gml:Polygon>
          </gml:surfaceMember>
        </gml:MultiSurface>
      </bldg:lod0FootPrint>
      <bldg:lod0RoofEdge>
        <gml:MultiSurface>
          <gml:surfaceMember>
            <gml:Polygon gml:id="70249278-3bf5-47ef-bd8f-11c5177e9dcf">
              <gml:exterior>
                <gml:LinearRing>
                  <gml:posList>60.0 0.0 17.05 68.67 0.0 17.05 68.67 7.37 17.05 60.0 7.37 17.05 60.0 0.0 17.05</gml:posList>
                </gml:LinearRing>
              </gml:exterior>
            </gml:Polygon>
          </gml:surfaceMember>
        </gml:MultiSurface>
      </bldg:lod0RoofEdge>
    </bldg:Building>
  </cityObjectMember>
</CityModel>
