<?xml version="1.0" encoding="utf-8"?>
<!-- Generated by Random3Dcity (http://github.com/tudelft3d/Random3Dcity), a tool developed by Filip Biljecki at TU Delft. Version: 2015-03-11. -->
<CityModel xmlns:veg="http://www.opengis.net/citygml/vegetation/2.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xAL="urn:oasis:names:tc:ciq:xsdschema:xAL:2.0" xmlns:dem="http://www.opengis.net/citygml/relief/2.0" xmlns:gml="http://www.opengis.net/gml" xmlns:fme="http://www.safe.com/xml/xmltables" xmlns:tran="http://www.opengis.net/citygml/transportation/2.0" xmlns:bldg="http://www.opengis.net/citygml/building/2.0" xmlns:xlink="http://www.w3.org/1999/xlink" xmlns="http://www.opengis.net/citygml/2.0">
  <gml:name>LOD0_0</gml:name>
  <gml:boundedBy>
    <gml:Envelope srsDimension="3" srsName="EPSG:28992">
      <gml:lowerCorner>0 0 0</gml:lowerCorner>
      <gml:upperCorner>4000 4000 25</gml:upperCorner>
    </gml:Envelope>
  </gml:boundedBy>
  <cityObjectMember>
    <bldg:Building gml:id="caf33126-a68b-4f61-a80a-aa52210befb5">
      <bldg:roofType>Flat</bldg:roofType>
      <bldg:yearOfConstruction>1953</bldg:yearOfConstruction>
      <bldg:function>Industrial</bldg:function>
      <bldg:storeysAboveGround>3</bldg:storeysAboveGround>
      <bldg:storeysAboveGround>3</bldg:storeysAboveGround>
      <bldg:lod0FootPrint>
        <gml:MultiSurface>
          <gml:surfaceMember>
            <gml:Polygon gml:id="e858ca98-44ef-4075-ad9e-8754d4d33418">
              <gml:exterior>
                <gml:LinearRing>
                  <gml:posList>0.0 0.0 0.0 54.0 0.0 0.0 54.0 54.0 0.0 0.0 54.0 0.0 0.0 0.0 0.0</gml:posList>
                </gml:LinearRing>
              </gml:exterior>
            </gml:Polygon>
          </gml:surfaceMember>
        </gml:MultiSurface>
      </bldg:lod0FootPrint>
    </bldg:Building>
  </cityObjectMember>
  <cityObjectMember>
    <bldg:Building gml:id="6b995b26-b59f-4e89-81ec-6c6aedb26c2b">
      <bldg:roofType>Flat</bldg:roofType>
      <bldg:yearOfConstruction>2014</bldg:yearOfConstruction>
      <bldg:function>Industrial</bldg:function>
      <bldg:storeysAboveGround>4</bldg:storeysAboveGround>
      <bldg:storeysAboveGround>4</bldg:storeysAboveGround>
      <bldg:lod0FootPrint>
        <gml:MultiSurface>
          <gml:surfaceMember>
            <gml:Polygon gml:id="3dbe18d5-ea45-4be5-8f03-77cef0b05f42">
              <gml:exterior>
                <gml:LinearRing>
                  <gml:posList>0.0 60.0 0.0 54.0 60.0 0.0 54.0 114.0 0.0 0.0 114.0 0.0 0.0 60.0 0.0</gml:posList>
                </gml:LinearRing>
              </gml:exterior>
            </gml:Polygon>
          </gml:surfaceMember>
        </gml:MultiSurface>
      </bldg:lod0FootPrint>
    </bldg:Building>
  </cityObjectMember>
  <cityObjectMember>
    <bldg:Building gml:id="9521318f-6228-4eef-ad4a-f61a71ecac3c">
      <bldg:roofType>Flat</bldg:roofType>
      <bldg:yearOfConstruction>1952</bldg:yearOfConstruction>
      <bldg:function>Residential</bldg:function>
      <bldg:storeysAboveGround>1</bldg:storeysAboveGround>
      <bldg:storeysAboveGround>1</bldg:storeysAboveGround>
      <bldg:lod0FootPrint>
        <gml:MultiSurface>
          <gml:surfaceMember>
            <gml:Polygon gml:id="24b99e19-d33f-4954-b9cd-f266b1c6fcca">
              <gml:exterior>
                <gml:LinearRing>
                  <gml:posList>60.0 0.0 0.0 114.0 0.0 0.0 114.0 54.0 0.0 60.0 54.0 0.0 60.0 0.0 0.0</gml:posList>
                </gml:LinearRing>
              </gml:exterior>
            </gml:Polygon>
          </gml:surfaceMember>
        </gml:MultiSurface>
      </bldg:lod0FootPrint>
    </bldg:Building>
  </cityObjectMember>
  <cityObjectMember>
    <bldg:Building gml:id="1c94bc05-5633-48c7-9365-81dee85cb22f">
      <bldg:roofType>Flat</bldg:roofType>
      <bldg:yearOfConstruction>1964</bldg:yearOfConstruction>
      <bldg:function>Residential</bldg:function>
      <bldg:storeysAboveGround>4</bldg:storeysAboveGround>
      <bldg:storeysAboveGround>4</bldg:storeysAboveGround>
      <bldg:lod0FootPrint>
        <gml:MultiSurface>
          <gml:surfaceMember>
            <gml:Polygon gml:id="16d8c79a-d6d8-4977-a17f-be8dc2f83b8d">
              <gml:exterior>
                <gml:LinearRing>
                  <gml:posList>60.0 60.0 0.0 114.0 60.0 0.0 114.0 114.0 0.0 60.0 114.0 0.0 60.0 60.0 0.0</gml:posList>
                </gml:LinearRing>
              </gml:exterior>
            </gml:Polygon>
          </gml:surfaceMember>
        </gml:MultiSurface>
      </bldg:lod0FootPrint>
    </bldg:Building>
  </cityObjectMember>
</CityModel>
