<?xml version="1.0" encoding="utf-8"?>
<!-- Generated by Random3Dcity (http://github.com/tudelft3d/Random3Dcity), a tool developed by Filip Biljecki at TU Delft. Version: 2015-03-11. -->
<CityModel xmlns:veg="http://www.opengis.net/citygml/vegetation/2.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xAL="urn:oasis:names:tc:ciq:xsdschema:xAL:2.0" xmlns:dem="http://www.opengis.net/citygml/relief/2.0" xmlns:gml="http://www.opengis.net/gml" xmlns:fme="http://www.safe.com/xml/xmltables" xmlns:tran="http://www.opengis.net/citygml/transportation/2.0" xmlns:bldg="http://www.opengis.net/citygml/building/2.0" xmlns:xlink="http://www.w3.org/1999/xlink" xmlns="http://www.opengis.net/citygml/2.0">
  <gml:name>LOD1_1_F0_H3</gml:name>
  <gml:boundedBy>
    <gml:Envelope srsDimension="3" srsName="EPSG:28992">
      <gml:lowerCorner>0 0 0</gml:lowerCorner>
      <gml:upperCorner>4000 4000 25</gml:upperCorner>
    </gml:Envelope>
  </gml:boundedBy>
  <cityObjectMember>
    <bldg:Building gml:id="d7c0e63f-6ec7-4ae9-926b-462f476c8c3a">
      <bldg:roofType>Hipped</bldg:roofType>
      <bldg:yearOfConstruction>1963</bldg:yearOfConstruction>
      <bldg:function>Residential</bldg:function>
      <bldg:storeysAboveGround>2</bldg:storeysAboveGround>
      <bldg:lod1MultiSurface>
        <gml:MultiSurface>
          <gml:surfaceMember>
            <gml:Polygon gml:id="f598f1a6-d6c6-4421-8d7c-ed091ae60cc3">
              <gml:exterior>
                <gml:LinearRing>
                  <gml:posList>0.0 0.0 0.0 7.95 0.0 0.0 7.95 0.0 7.65487421384 0.0 0.0 7.65487421384 0.0 0.0 0.0</gml:posList>
                </gml:LinearRing>
              </gml:exterior>
            </gml:Polygon>
            <gml:Polygon gml:id="35e743aa-a523-490b-abee-6696072c9a16">
              <gml:exterior>
                <gml:LinearRing>
                  <gml:posList>7.95 6.11 0.0 0.0 6.11 0.0 0.0 6.11 7.65487421384 7.95 6.11 7.65487421384 7.95 6.11 0.0</gml:posList>
                </gml:LinearRing>
              </gml:exterior>
            </gml:Polygon>
            <gml:Polygon gml:id="8c3876dd-2a72-4ca1-b298-646e52305b3f">
              <gml:exterior>
                <gml:LinearRing>
                  <gml:posList>0.0 6.11 0.0 0.0 0.0 0.0 0.0 0.0 7.65487421384 0.0 6.11 7.65487421384 0.0 6.11 0.0</gml:posList>
                </gml:LinearRing>
              </gml:exterior>
            </gml:Polygon>
            <gml:Polygon gml:id="25d1dfce-e697-4178-a20e-e7fcfe137737">
              <gml:exterior>
                <gml:LinearRing>
                  <gml:posList>7.95 0.0 0.0 7.95 6.11 0.0 7.95 6.11 7.65487421384 7.95 0.0 7.65487421384 7.95 0.0 0.0</gml:posList>
                </gml:LinearRing>
              </gml:exterior>
            </gml:Polygon>
            <gml:Polygon gml:id="2189f3ba-db57-4727-a9d4-d5ebef7a781d">
              <gml:exterior>
                <gml:LinearRing>
                  <gml:posList>0.0 0.0 0.0 0.0 6.11 0.0 7.95 6.11 0.0 7.95 0.0 0.0 0.0 0.0 0.0</gml:posList>
                </gml:LinearRing>
              </gml:exterior>
            </gml:Polygon>
            <gml:Polygon gml:id="eb44a175-8046-4b0c-b13e-3b7fc1e47219">
              <gml:exterior>
                <gml:LinearRing>
                  <gml:posList>0.0 0.0 7.65487421384 7.95 0.0 7.65487421384 7.95 6.11 7.65487421384 0.0 6.11 7.65487421384 0.0 0.0 7.65487421384</gml:posList>
                </gml:LinearRing>
              </gml:exterior>
            </gml:Polygon>
          </gml:surfaceMember>
        </gml:MultiSurface>
      </bldg:lod1MultiSurface>
    </bldg:Building>
  </cityObjectMember>
  <cityObjectMember>
    <bldg:Building gml:id="693f46c0-a345-478a-93b0-ea01615fb40c">
      <bldg:roofType>Shed</bldg:roofType>
      <bldg:yearOfConstruction>2009</bldg:yearOfConstruction>
      <bldg:function>Residential</bldg:function>
      <bldg:storeysAboveGround>2</bldg:storeysAboveGround>
      <bldg:lod1MultiSurface>
        <gml:MultiSurface>
          <gml:surfaceMember>
            <gml:Polygon gml:id="fcd2601c-0719-4f59-834c-af7f5a40e71b">
              <gml:exterior>
                <gml:LinearRing>
                  <gml:posList>0.0 20.0 0.0 9.27 20.0 0.0 9.27 20.0 8.145 0.0 20.0 8.145 0.0 20.0 0.0</gml:posList>
                </gml:LinearRing>
              </gml:exterior>
            </gml:Polygon>
            <gml:Polygon gml:id="18900058-eeb7-4f16-8c69-866d91543a6e">
              <gml:exterior>
                <gml:LinearRing>
                  <gml:posList>9.27 28.61 0.0 0.0 28.61 0.0 0.0 28.61 8.145 9.27 28.61 8.145 9.27 28.61 0.0</gml:posList>
                </gml:LinearRing>
              </gml:exterior>
            </gml:Polygon>
            <gml:Polygon gml:id="277f9a79-3716-4741-8330-6555f5459697">
              <gml:exterior>
                <gml:LinearRing>
                  <gml:posList>0.0 28.61 0.0 0.0 20.0 0.0 0.0 20.0 8.145 0.0 28.61 8.145 0.0 28.61 0.0</gml:posList>
                </gml:LinearRing>
              </gml:exterior>
            </gml:Polygon>
            <gml:Polygon gml:id="dc23b31e-a125-4150-9494-7fa093d4c3e6">
              <gml:exterior>
                <gml:LinearRing>
                  <gml:posList>9.27 20.0 0.0 9.27 28.61 0.0 9.27 28.61 8.145 9.27 20.0 8.145 9.27 20.0 0.0</gml:posList>
                </gml:LinearRing>
              </gml:exterior>
            </gml:Polygon>
            <gml:Polygon gml:id="904ad8ba-cc96-47c3-b938-6b3642d4270f">
              <gml:exterior>
                <gml:LinearRing>
                  <gml:posList>0.0 20.0 0.0 0.0 28.61 0.0 9.27 28.61 0.0 9.27 20.0 0.0 0.0 20.0 0.0</gml:posList>
                </gml:LinearRing>
              </gml:exterior>
            </gml:Polygon>
            <gml:Polygon gml:id="28338bde-cd73-4cc3-bf3f-4df859935cf5">
              <gml:exterior>
                <gml:LinearRing>
                  <gml:posList>0.0 20.0 8.145 9.27 20.0 8.145 9.27 28.61 8.145 0.0 28.61 8.145 0.0 20.0 8.145</gml:posList>
                </gml:LinearRing>
              </gml:exterior>
            </gml:Polygon>
          </gml:surfaceMember>
        </gml:MultiSurface>
      </bldg:lod1MultiSurface>
    </bldg:Building>
  </cityObjectMember>
  <cityObjectMember>
    <bldg:Building gml:id="e5f72295-e816-4b06-a0d1-2453f5e453bb">
      <bldg:roofType>Gabled</bldg:roofType>
      <bldg:yearOfConstruction>2002</bldg:yearOfConstruction>
      <bldg:function>Residential</bldg:function>
      <bldg:storeysAboveGround>2</bldg:storeysAboveGround>
      <bldg:lod1MultiSurface>
        <gml:MultiSurface>
          <gml:surfaceMember>
            <gml:Polygon gml:id="224071d6-7021-44d9-93ed-ad2a33ea81ce">
              <gml:exterior>
                <gml:LinearRing>
                  <gml:posList>0.0 40.0 0.0 5.84 40.0 0.0 5.84 40.0 7.5875 0.0 40.0 7.5875 0.0 40.0 0.0</gml:posList>
                </gml:LinearRing>
              </gml:exterior>
            </gml:Polygon>
            <gml:Polygon gml:id="f90dbdb6-e733-4517-803d-d9a9f1207e08">
              <gml:exterior>
                <gml:LinearRing>
                  <gml:posList>5.84 47.13 0.0 0.0 47.13 0.0 0.0 47.13 7.5875 5.84 47.13 7.5875 5.84 47.13 0.0</gml:posList>
                </gml:LinearRing>
              </gml:exterior>
            </gml:Polygon>
            <gml:Polygon gml:id="fb8e4af8-de4c-4420-bba3-672dfe6b1144">
              <gml:exterior>
                <gml:LinearRing>
                  <gml:posList>0.0 47.13 0.0 0.0 40.0 0.0 0.0 40.0 7.5875 0.0 47.13 7.5875 0.0 47.13 0.0</gml:posList>
                </gml:LinearRing>
              </gml:exterior>
            </gml:Polygon>
            <gml:Polygon gml:id="f818ebbc-238a-492e-97a5-e2d3cb9098a6">
              <gml:exterior>
                <gml:LinearRing>
                  <gml:posList>5.84 40.0 0.0 5.84 47.13 0.0 5.84 47.13 7.5875 5.84 40.0 7.5875 5.84 40.0 0.0</gml:posList>
                </gml:LinearRing>
              </gml:exterior>
            </gml:Polygon>
            <gml:Polygon gml:id="2f591d0e-f40f-4561-a41b-a71039c06d02">
              <gml:exterior>
                <gml:LinearRing>
                  <gml:posList>0.0 40.0 0.0 0.0 47.13 0.0 5.84 47.13 0.0 5.84 40.0 0.0 0.0 40.0 0.0</gml:posList>
                </gml:LinearRing>
              </gml:exterior>
            </gml:Polygon>
            <gml:Polygon gml:id="b39c1ee8-8830-4a84-9ce6-3f3d13ffd2f5">
              <gml:exterior>
                <gml:LinearRing>
                  <gml:posList>0.0 40.0 7.5875 5.84 40.0 7.5875 5.84 47.13 7.5875 0.0 47.13 7.5875 0.0 40.0 7.5875</gml:posList>
                </gml:LinearRing>
              </gml:exterior>
            </gml:Polygon>
          </gml:surfaceMember>
        </gml:MultiSurface>
      </bldg:lod1MultiSurface>
    </bldg:Building>
  </cityObjectMember>
  <cityObjectMember>
    <bldg:Building gml:id="6ca837fc-523d-4217-b82d-4906fb0404fd">
      <bldg:roofType>Shed</bldg:roofType>
      <bldg:yearOfConstruction>1948</bldg:yearOfConstruction>
      <bldg:function>Residential</bldg:function>
      <bldg:storeysAboveGround>2</bldg:storeysAboveGround>
      <bldg:lod1MultiSurface>
        <gml:MultiSurface>
          <gml:surfaceMember>
            <gml:Polygon gml:id="7721b4d4-a044-43c7-ac3c-8742f8c90746">
              <gml:exterior>
                <gml:LinearRing>
                  <gml:posList>20.0 0.0 0.0 23.72 0.0 0.0 23.72 0.0 8.57 20.0 0.0 8.57 20.0 0.0 0.0</gml:posList>
                </gml:LinearRing>
              </gml:exterior>
            </gml:Polygon>
            <gml:Polygon gml:id="0aa49d3a-2628-4ee9-9e43-5aa3c4d45321">
              <gml:exterior>
                <gml:LinearRing>
                  <gml:posList>23.72 9.83 0.0 20.0 9.83 0.0 20.0 9.83 8.57 23.72 9.83 8.57 23.72 9.83 0.0</gml:posList>
                </gml:LinearRing>
              </gml:exterior>
            </gml:Polygon>
            <gml:Polygon gml:id="90372b1b-3422-470f-a148-ab3ae2af8c71">
              <gml:exterior>
                <gml:LinearRing>
                  <gml:posList>20.0 9.83 0.0 20.0 0.0 0.0 20.0 0.0 8.57 20.0 9.83 8.57 20.0 9.83 0.0</gml:posList>
                </gml:LinearRing>
              </gml:exterior>
            </gml:Polygon>
            <gml:Polygon gml:id="2b9749fd-3ff6-43d0-b1f2-87e4c3cd4651">
              <gml:exterior>
                <gml:LinearRing>
                  <gml:posList>23.72 0.0 0.0 23.72 9.83 0.0 23.72 9.83 8.57 23.72 0.0 8.57 23.72 0.0 0.0</gml:posList>
                </gml:LinearRing>
              </gml:exterior>
            </gml:Polygon>
            <gml:Polygon gml:id="c8167b6b-ae0a-4203-8468-52d4270c34e9">
              <gml:exterior>
                <gml:LinearRing>
                  <gml:posList>20.0 0.0 0.0 20.0 9.83 0.0 23.72 9.83 0.0 23.72 0.0 0.0 20.0 0.0 0.0</gml:posList>
                </gml:LinearRing>
              </gml:exterior>
            </gml:Polygon>
            <gml:Polygon gml:id="a9d84fdd-f37e-42f5-8234-e7941396a575">
              <gml:exterior>
                <gml:LinearRing>
                  <gml:posList>20.0 0.0 8.57 23.72 0.0 8.57 23.72 9.83 8.57 20.0 9.83 8.57 20.0 0.0 8.57</gml:posList>
                </gml:LinearRing>
              </gml:exterior>
            </gml:Polygon>
          </gml:surfaceMember>
        </gml:MultiSurface>
      </bldg:lod1MultiSurface>
    </bldg:Building>
  </cityObjectMember>
  <cityObjectMember>
    <bldg:Building gml:id="37b27226-1d6a-40ae-9a8e-df67172b9e76">
      <bldg:roofType>Flat</bldg:roofType>
      <bldg:yearOfConstruction>1955</bldg:yearOfConstruction>
      <bldg:function>Industrial</bldg:function>
      <bldg:storeysAboveGround>4</bldg:storeysAboveGround>
      <bldg:lod1MultiSurface>
        <gml:MultiSurface>
          <gml:surfaceMember>
            <gml:Polygon gml:id="cb4c578b-bde8-4ea9-bd07-41f3b551ceb7">
              <gml:exterior>
                <gml:LinearRing>
                  <gml:posList>20.0 20.0 0.0 25.17 20.0 0.0 25.17 20.0 13.2 20.0 20.0 13.2 20.0 20.0 0.0</gml:posList>
                </gml:LinearRing>
              </gml:exterior>
            </gml:Polygon>
            <gml:Polygon gml:id="2609eddc-ef72-430f-8677-e5d1c7da9a14">
              <gml:exterior>
                <gml:LinearRing>
                  <gml:posList>25.17 24.23 0.0 20.0 24.23 0.0 20.0 24.23 13.2 25.17 24.23 13.2 25.17 24.23 0.0</gml:posList>
                </gml:LinearRing>
              </gml:exterior>
            </gml:Polygon>
            <gml:Polygon gml:id="047b5236-52ac-4510-b9ea-fbac60c33c8b">
              <gml:exterior>
                <gml:LinearRing>
                  <gml:posList>20.0 24.23 0.0 20.0 20.0 0.0 20.0 20.0 13.2 20.0 24.23 13.2 20.0 24.23 0.0</gml:posList>
                </gml:LinearRing>
              </gml:exterior>
            </gml:Polygon>
            <gml:Polygon gml:id="9a850990-f0cc-4c4a-95b4-7ac7d9653abd">
              <gml:exterior>
                <gml:LinearRing>
                  <gml:posList>25.17 20.0 0.0 25.17 24.23 0.0 25.17 24.23 13.2 25.17 20.0 13.2 25.17 20.0 0.0</gml:posList>
                </gml:LinearRing>
              </gml:exterior>
            </gml:Polygon>
            <gml:Polygon gml:id="a5d3d0bb-6a5f-4263-8830-7328b07e4df9">
              <gml:exterior>
                <gml:LinearRing>
                  <gml:posList>20.0 20.0 0.0 20.0 24.23 0.0 25.17 24.23 0.0 25.17 20.0 0.0 20.0 20.0 0.0</gml:posList>
                </gml:LinearRing>
              </gml:exterior>
            </gml:Polygon>
            <gml:Polygon gml:id="c262eaca-ee4f-4e60-9a77-da74ef7eb580">
              <gml:exterior>
                <gml:LinearRing>
                  <gml:posList>20.0 20.0 13.2 25.17 20.0 13.2 25.17 24.23 13.2 20.0 24.23 13.2 20.0 20.0 13.2</gml:posList>
                </gml:LinearRing>
              </gml:exterior>
            </gml:Polygon>
          </gml:surfaceMember>
        </gml:MultiSurface>
      </bldg:lod1MultiSurface>
    </bldg:Building>
  </cityObjectMember>
  <cityObjectMember>
    <bldg:Building gml:id="353a591b-01e4-49a6-8fd3-360313f6ca7f">
      <bldg:roofType>Hipped</bldg:roofType>
      <bldg:yearOfConstruction>1988</bldg:yearOfConstruction>
      <bldg:function>Residential</bldg:function>
      <bldg:storeysAboveGround>2</bldg:storeysAboveGround>
      <bldg:lod1MultiSurface>
        <gml:MultiSurface>
          <gml:surfaceMember>
            <gml:Polygon gml:id="6a1067df-63df-4f6e-be99-da47c245885b">
              <gml:exterior>
                <gml:LinearRing>
                  <gml:posList>20.0 40.0 0.0 24.05 40.0 0.0 24.05 40.0 7.75197530864 20.0 40.0 7.75197530864 20.0 40.0 0.0</gml:posList>
                </gml:LinearRing>
              </gml:exterior>
            </gml:Polygon>
            <gml:Polygon gml:id="34e3848f-17d3-4379-962d-2c2236c88e01">
              <gml:exterior>
                <gml:LinearRing>
                  <gml:posList>24.05 49.63 0.0 20.0 49.63 0.0 20.0 49.63 7.75197530864 24.05 49.63 7.75197530864 24.05 49.63 0.0</gml:posList>
                </gml:LinearRing>
              </gml:exterior>
            </gml:Polygon>
            <gml:Polygon gml:id="312dd6e2-6915-4230-a793-677165afe031">
              <gml:exterior>
                <gml:LinearRing>
                  <gml:posList>20.0 49.63 0.0 20.0 40.0 0.0 20.0 40.0 7.75197530864 20.0 49.63 7.75197530864 20.0 49.63 0.0</gml:posList>
                </gml:LinearRing>
              </gml:exterior>
            </gml:Polygon>
            <gml:Polygon gml:id="8bfbfc10-a85a-45d3-ada5-dad978fabe94">
              <gml:exterior>
                <gml:LinearRing>
                  <gml:posList>24.05 40.0 0.0 24.05 49.63 0.0 24.05 49.63 7.75197530864 24.05 40.0 7.75197530864 24.05 40.0 0.0</gml:posList>
                </gml:LinearRing>
              </gml:exterior>
            </gml:Polygon>
            <gml:Polygon gml:id="ddad7336-8c28-4153-898a-ed09a30cf33f">
              <gml:exterior>
                <gml:LinearRing>
                  <gml:posList>20.0 40.0 0.0 20.0 49.63 0.0 24.05 49.63 0.0 24.05 40.0 0.0 20.0 40.0 0.0</gml:posList>
                </gml:LinearRing>
              </gml:exterior>
            </gml:Polygon>
            <gml:Polygon gml:id="57cecde5-97aa-4912-8ae9-8a59e9bff7e1">
              <gml:exterior>
                <gml:LinearRing>
                  <gml:posList>20.0 40.0 7.75197530864 24.05 40.0 7.75197530864 24.05 49.63 7.75197530864 20.0 49.63 7.75197530864 20.0 40.0 7.75197530864</gml:posList>
                </gml:LinearRing>
              </gml:exterior>
            </gml:Polygon>
          </gml:surfaceMember>
        </gml:MultiSurface>
      </bldg:lod1MultiSurface>
    </bldg:Building>
  </cityObjectMember>
  <cityObjectMember>
    <bldg:Building gml:id="249246ba-d9f5-48e8-8b69-1c0677375c5a">
      <bldg:roofType>Flat</bldg:roofType>
      <bldg:yearOfConstruction>2004</bldg:yearOfConstruction>
      <bldg:function>Industrial</bldg:function>
      <bldg:storeysAboveGround>5</bldg:storeysAboveGround>
      <bldg:lod1MultiSurface>
        <gml:MultiSurface>
          <gml:surfaceMember>
            <gml:Polygon gml:id="d9a7e2ab-e6df-4243-a916-4c78396911ee">
              <gml:exterior>
                <gml:LinearRing>
                  <gml:posList>40.0 0.0 0.0 46.11 0.0 0.0 46.11 0.0 16.6 40.0 0.0 16.6 40.0 0.0 0.0</gml:posList>
                </gml:LinearRing>
              </gml:exterior>
            </gml:Polygon>
            <gml:Polygon gml:id="0b318acc-c837-4990-aa77-9d3e7611a17e">
              <gml:exterior>
                <gml:LinearRing>
                  <gml:posList>46.11 3.68 0.0 40.0 3.68 0.0 40.0 3.68 16.6 46.11 3.68 16.6 46.11 3.68 0.0</gml:posList>
                </gml:LinearRing>
              </gml:exterior>
            </gml:Polygon>
            <gml:Polygon gml:id="b35da2f9-152e-4de8-a8c0-1a238856033f">
              <gml:exterior>
                <gml:LinearRing>
                  <gml:posList>40.0 3.68 0.0 40.0 0.0 0.0 40.0 0.0 16.6 40.0 3.68 16.6 40.0 3.68 0.0</gml:posList>
                </gml:LinearRing>
              </gml:exterior>
            </gml:Polygon>
            <gml:Polygon gml:id="2b5ce941-9705-48e3-82fb-d9a071bfd24b">
              <gml:exterior>
                <gml:LinearRing>
                  <gml:posList>46.11 0.0 0.0 46.11 3.68 0.0 46.11 3.68 16.6 46.11 0.0 16.6 46.11 0.0 0.0</gml:posList>
                </gml:LinearRing>
              </gml:exterior>
            </gml:Polygon>
            <gml:Polygon gml:id="14ddfdc5-11bc-43c5-85ef-4031f1fb68fb">
              <gml:exterior>
                <gml:LinearRing>
                  <gml:posList>40.0 0.0 0.0 40.0 3.68 0.0 46.11 3.68 0.0 46.11 0.0 0.0 40.0 0.0 0.0</gml:posList>
                </gml:LinearRing>
              </gml:exterior>
            </gml:Polygon>
            <gml:Polygon gml:id="f24b01de-48c6-4a4b-9685-550a7294efb8">
              <gml:exterior>
                <gml:LinearRing>
                  <gml:posList>40.0 0.0 16.6 46.11 0.0 16.6 46.11 3.68 16.6 40.0 3.68 16.6 40.0 0.0 16.6</gml:posList>
                </gml:LinearRing>
              </gml:exterior>
            </gml:Polygon>
          </gml:surfaceMember>
        </gml:MultiSurface>
      </bldg:lod1MultiSurface>
    </bldg:Building>
  </cityObjectMember>
  <cityObjectMember>
    <bldg:Building gml:id="0d252789-4485-452f-85e1-52c5eb975b10">
      <bldg:roofType>Flat</bldg:roofType>
      <bldg:yearOfConstruction>1948</bldg:yearOfConstruction>
      <bldg:function>Residential</bldg:function>
      <bldg:storeysAboveGround>2</bldg:storeysAboveGround>
      <bldg:lod1MultiSurface>
        <gml:MultiSurface>
          <gml:surfaceMember>
            <gml:Polygon gml:id="20e17884-6ab5-4848-b4e5-29f5db9ed2f9">
              <gml:exterior>
                <gml:LinearRing>
                  <gml:posList>40.0 20.0 0.0 48.21 20.0 0.0 48.21 20.0 6.98 40.0 20.0 6.98 40.0 20.0 0.0</gml:posList>
                </gml:LinearRing>
              </gml:exterior>
            </gml:Polygon>
            <gml:Polygon gml:id="2bba4f31-73df-4422-9fc5-7b27ac2d0546">
              <gml:exterior>
                <gml:LinearRing>
                  <gml:posList>48.21 29.57 0.0 40.0 29.57 0.0 40.0 29.57 6.98 48.21 29.57 6.98 48.21 29.57 0.0</gml:posList>
                </gml:LinearRing>
              </gml:exterior>
            </gml:Polygon>
            <gml:Polygon gml:id="63dc3d91-9ed0-4474-b218-da34630be94d">
              <gml:exterior>
                <gml:LinearRing>
                  <gml:posList>40.0 29.57 0.0 40.0 20.0 0.0 40.0 20.0 6.98 40.0 29.57 6.98 40.0 29.57 0.0</gml:posList>
                </gml:LinearRing>
              </gml:exterior>
            </gml:Polygon>
            <gml:Polygon gml:id="00cf646b-5161-4404-b969-081ea727e079">
              <gml:exterior>
                <gml:LinearRing>
                  <gml:posList>48.21 20.0 0.0 48.21 29.57 0.0 48.21 29.57 6.98 48.21 20.0 6.98 48.21 20.0 0.0</gml:posList>
                </gml:LinearRing>
              </gml:exterior>
            </gml:Polygon>
            <gml:Polygon gml:id="ac705acf-7125-4cdf-8e31-fbef59bfb40e">
              <gml:exterior>
                <gml:LinearRing>
                  <gml:posList>40.0 20.0 0.0 40.0 29.57 0.0 48.21 29.57 0.0 48.21 20.0 0.0 40.0 20.0 0.0</gml:posList>
                </gml:LinearRing>
              </gml:exterior>
            </gml:Polygon>
            <gml:Polygon gml:id="8d64db7e-eb18-4221-b7b4-0dc1ef575050">
              <gml:exterior>
                <gml:LinearRing>
                  <gml:posList>40.0 20.0 6.98 48.21 20.0 6.98 48.21 29.57 6.98 40.0 29.57 6.98 40.0 20.0 6.98</gml:posList>
                </gml:LinearRing>
              </gml:exterior>
            </gml:Polygon>
          </gml:surfaceMember>
        </gml:MultiSurface>
      </bldg:lod1MultiSurface>
    </bldg:Building>
  </cityObjectMember>
  <cityObjectMember>
    <bldg:Building gml:id="5644769e-43bd-4244-9984-56f1e99ab43e">
      <bldg:roofType>Flat</bldg:roofType>
      <bldg:yearOfConstruction>1962</bldg:yearOfConstruction>
      <bldg:function>Residential</bldg:function>
      <bldg:storeysAboveGround>5</bldg:storeysAboveGround>
      <bldg:lod1MultiSurface>
        <gml:MultiSurface>
          <gml:surfaceMember>
            <gml:Polygon gml:id="c0441a66-6f4a-4d25-ba05-3f796cfff9d6">
              <gml:exterior>
                <gml:LinearRing>
                  <gml:posList>40.0 40.0 0.0 45.07 40.0 0.0 45.07 40.0 16.1 40.0 40.0 16.1 40.0 40.0 0.0</gml:posList>
                </gml:LinearRing>
              </gml:exterior>
            </gml:Polygon>
            <gml:Polygon gml:id="c83fa2fe-30b0-41d7-9c61-4f0420f69bc8">
              <gml:exterior>
                <gml:LinearRing>
                  <gml:posList>45.07 48.57 0.0 40.0 48.57 0.0 40.0 48.57 16.1 45.07 48.57 16.1 45.07 48.57 0.0</gml:posList>
                </gml:LinearRing>
              </gml:exterior>
            </gml:Polygon>
            <gml:Polygon gml:id="9e27c637-dd30-4169-ae69-f443f40b79a6">
              <gml:exterior>
                <gml:LinearRing>
                  <gml:posList>40.0 48.57 0.0 40.0 40.0 0.0 40.0 40.0 16.1 40.0 48.57 16.1 40.0 48.57 0.0</gml:posList>
                </gml:LinearRing>
              </gml:exterior>
            </gml:Polygon>
            <gml:Polygon gml:id="8453b2bb-0fd4-4c7d-9f25-3926156b691c">
              <gml:exterior>
                <gml:LinearRing>
                  <gml:posList>45.07 40.0 0.0 45.07 48.57 0.0 45.07 48.57 16.1 45.07 40.0 16.1 45.07 40.0 0.0</gml:posList>
                </gml:LinearRing>
              </gml:exterior>
            </gml:Polygon>
            <gml:Polygon gml:id="7cc59afa-fd1e-4893-be58-7101c936ccdf">
              <gml:exterior>
                <gml:LinearRing>
                  <gml:posList>40.0 40.0 0.0 40.0 48.57 0.0 45.07 48.57 0.0 45.07 40.0 0.0 40.0 40.0 0.0</gml:posList>
                </gml:LinearRing>
              </gml:exterior>
            </gml:Polygon>
            <gml:Polygon gml:id="c2a6fa73-5418-4e09-a9bb-7d8648204244">
              <gml:exterior>
                <gml:LinearRing>
                  <gml:posList>40.0 40.0 16.1 45.07 40.0 16.1 45.07 48.57 16.1 40.0 48.57 16.1 40.0 40.0 16.1</gml:posList>
                </gml:LinearRing>
              </gml:exterior>
            </gml:Polygon>
          </gml:surfaceMember>
        </gml:MultiSurface>
      </bldg:lod1MultiSurface>
    </bldg:Building>
  </cityObjectMember>
  <cityObjectMember>
    <bldg:Building gml:id="57a35cd2-2307-4dc8-9081-d3bb5ae7f6e2">
      <bldg:roofType>Flat</bldg:roofType>
      <bldg:yearOfConstruction>1996</bldg:yearOfConstruction>
      <bldg:function>Residential</bldg:function>
      <bldg:storeysAboveGround>5</bldg:storeysAboveGround>
      <bldg:lod1MultiSurface>
        <gml:MultiSurface>
          <gml:surfaceMember>
            <gml:Polygon gml:id="616e8610-abf8-43a4-8965-5ac36844d155">
              <gml:exterior>
                <gml:LinearRing>
                  <gml:posList>60.0 0.0 0.0 68.67 0.0 0.0 68.67 0.0 17.05 60.0 0.0 17.05 60.0 0.0 0.0</gml:posList>
                </gml:LinearRing>
              </gml:exterior>
            </gml:Polygon>
            <gml:Polygon gml:id="eab94b0e-bd1d-446f-968b-9ac797c966ad">
              <gml:exterior>
                <gml:LinearRing>
                  <gml:posList>68.67 7.37 0.0 60.0 7.37 0.0 60.0 7.37 17.05 68.67 7.37 17.05 68.67 7.37 0.0</gml:posList>
                </gml:LinearRing>
              </gml:exterior>
            </gml:Polygon>
            <gml:Polygon gml:id="0b225228-6968-4e83-a598-ab75a1db4882">
              <gml:exterior>
                <gml:LinearRing>
                  <gml:posList>60.0 7.37 0.0 60.0 0.0 0.0 60.0 0.0 17.05 60.0 7.37 17.05 60.0 7.37 0.0</gml:posList>
                </gml:LinearRing>
              </gml:exterior>
            </gml:Polygon>
            <gml:Polygon gml:id="b54e2e0f-0bf7-4868-8fd1-fbd7e5c09f96">
              <gml:exterior>
                <gml:LinearRing>
                  <gml:posList>68.67 0.0 0.0 68.67 7.37 0.0 68.67 7.37 17.05 68.67 0.0 17.05 68.67 0.0 0.0</gml:posList>
                </gml:LinearRing>
              </gml:exterior>
            </gml:Polygon>
            <gml:Polygon gml:id="b96f4d9c-06b5-4d7b-8a7e-a188ab545f4c">
              <gml:exterior>
                <gml:LinearRing>
                  <gml:posList>60.0 0.0 0.0 60.0 7.37 0.0 68.67 7.37 0.0 68.67 0.0 0.0 60.0 0.0 0.0</gml:posList>
                </gml:LinearRing>
              </gml:exterior>
            </gml:Polygon>
            <gml:Polygon gml:id="65f04d82-0496-4be2-bb75-a728d7774f0e">
              <gml:exterior>
                <gml:LinearRing>
                  <gml:posList>60.0 0.0 17.05 68.67 0.0 17.05 68.67 7.37 17.05 60.0 7.37 17.05 60.0 0.0 17.05</gml:posList>
                </gml:LinearRing>
              </gml:exterior>
            </gml:Polygon>
          </gml:surfaceMember>
        </gml:MultiSurface>
      </bldg:lod1MultiSurface>
    </bldg:Building>
  </cityObjectMember>
</CityModel>
